Repository javascript-tutorial/it.javascript.info, pull requests merged in 2021-04, with the labels that each got.

#274 XMLHttpRequest
  5-network/08-xmlhttprequest/article.md
  5-network/08-xmlhttprequest/example.view/server.js
  5-network/08-xmlhttprequest/phones-async.view/server.js
  5-network/08-xmlhttprequest/phones.view/index.html
  5-network/08-xmlhttprequest/phones.view/server.js
  5-network/08-xmlhttprequest/post.view/server.js
Labels: 2n review done, review needed

#275 Resumable file upload
  5-network/09-resume-upload/article.md
  5-network/09-resume-upload/upload-resume.view/index.html
  5-network/09-resume-upload/upload-resume.view/server.js
  5-network/09-resume-upload/upload-resume.view/uploader.js
Labels: 2n review done, review needed

#276 From the orbital height
  8-web-components/1-webcomponents-intro/article.md
Labels: 2n review done, review needed

#273 Cross-window communication
  3-frames-and-windows/03-cross-window-communication/article.md
Labels: 2n review done, needs +1

#277 Custom elements
  8-web-components/2-custom-elements/1-live-timer/solution.md
  8-web-components/2-custom-elements/1-live-timer/solution.view/live-timer.js
  8-web-components/2-custom-elements/1-live-timer/source.view/index.html
  8-web-components/2-custom-elements/1-live-timer/source.view/live-timer.js
  8-web-components/2-custom-elements/1-live-timer/task.md
  8-web-components/2-custom-elements/article.md
Labels: 2n review done, needs +1

#278 The clickjacking attack
  3-frames-and-windows/06-clickjacking/article.md
  3-frames-and-windows/06-clickjacking/clickjacking-visible.view/index.html
  3-frames-and-windows/06-clickjacking/clickjacking.view/index.html
Labels: 2n review done, needs +1

#279 Element size and scrolling
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/solution.md
  2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/task.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/solution.md
  2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/ball-half/index.html
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.view/index.html
  2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
  2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/task.md
  2-ui/1-document/09-size-and-scroll/article.md
  2-ui/1-document/09-size-and-scroll/cssWidthScroll.view/index.html
  2-ui/1-document/09-size-and-scroll/metric.view/index.html
Labels: 2n review done, review needed

#281 Modifying document
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/solution.md
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/task.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.md
  2-ui/1-document/07-modifying-document/10-clock-setinterval/solution.view/index.html
  2-ui/1-document/07-modifying-document/10-clock-setinterval/source.view/index.html
  2-ui/1-document/07-modifying-document/10-clock-setinterval/task.md
  2-ui/1-document/07-modifying-document/11-append-to-list/solution.md
  2-ui/1-document/07-modifying-document/11-append-to-list/task.md
  2-ui/1-document/07-modifying-document/12-sort-table/solution.md
  2-ui/1-document/07-modifying-document/12-sort-table/source.view/index.html
  2-ui/1-document/07-modifying-document/12-sort-table/task.md
  2-ui/1-document/07-modifying-document/4-clear-elem/solution.md
  2-ui/1-document/07-modifying-document/4-clear-elem/task.md
  2-ui/1-document/07-modifying-document/5-why-aaa/solution.md
  2-ui/1-document/07-modifying-document/5-why-aaa/task.md
  2-ui/1-document/07-modifying-document/6-create-list/solution.md
  2-ui/1-document/07-modifying-document/6-create-list/task.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/build-tree-dom.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/innerhtml.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/solution.md
  2-ui/1-document/07-modifying-document/7-create-object-tree/source.view/index.html
  2-ui/1-document/07-modifying-document/7-create-object-tree/task.md
  2-ui/1-document/07-modifying-document/8-tree-count/solution.md
  2-ui/1-document/07-modifying-document/8-tree-count/solution.view/index.html
  2-ui/1-document/07-modifying-document/8-tree-count/source.view/index.html
  2-ui/1-document/07-modifying-document/8-tree-count/task.md
  2-ui/1-document/07-modifying-document/9-calendar-table/solution.md
  2-ui/1-document/07-modifying-document/9-calendar-table/solution.view/index.html
  2-ui/1-document/07-modifying-document/9-calendar-table/source.view/index.html
  2-ui/1-document/07-modifying-document/9-calendar-table/task.md
  2-ui/1-document/07-modifying-document/article.md
Labels: needs +1

#284 Window sizes and scrolling
  2-ui/1-document/10-size-and-scroll-window/article.md
Labels: needs +1

#285 CSS-animations
  7-animation/2-css-animations/1-animate-logo-css/solution.md
  7-animation/2-css-animations/1-animate-logo-css/task.md
  7-animation/2-css-animations/2-animate-logo-bezier-css/solution.md
  7-animation/2-css-animations/2-animate-logo-bezier-css/task.md
  7-animation/2-css-animations/3-animate-circle/task.md
  7-animation/2-css-animations/4-animate-circle-callback/task.md
  7-animation/2-css-animations/article.md
  7-animation/2-css-animations/boat.view/index.html
  7-animation/2-css-animations/boat.view/style.css
Labels: needs +1

#288 Escaping, special characters
  9-regular-expressions/07-regexp-escaping/article.md
Labels: needs +1

#294 Custom errors, extending Error
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
  1-js/10-error-handling/2-custom-errors/1-format-error/solution.md
  1-js/10-error-handling/2-custom-errors/1-format-error/task.md
  1-js/10-error-handling/index.md
Labels: needs +1

#286 Coordinates
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.md
  2-ui/1-document/11-coordinates/1-find-point-coordinates/solution.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/source.view/index.html
  2-ui/1-document/11-coordinates/1-find-point-coordinates/task.md
  2-ui/1-document/11-coordinates/2-position-at/solution.md
  2-ui/1-document/11-coordinates/2-position-at/solution.view/index.html
  2-ui/1-document/11-coordinates/2-position-at/source.view/index.html
  2-ui/1-document/11-coordinates/2-position-at/task.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.md
  2-ui/1-document/11-coordinates/3-position-at-absolute/solution.view/index.html
  2-ui/1-document/11-coordinates/3-position-at-absolute/task.md
  2-ui/1-document/11-coordinates/4-position-inside-absolute/task.md
  2-ui/1-document/11-coordinates/article.md
Labels: needs +1

#299 Sync
  1-js/02-first-steps/15-function-basics/article.md
  1-js/03-code-quality/05-testing-mocha/article.md
  1-js/03-code-quality/06-polyfills/article.md
  1-js/04-object-basics/04-object-methods/article.md
  1-js/05-data-types/08-weakmap-weakset/article.md
  1-js/05-data-types/09-keys-values-entries/article.md
  1-js/11-async/02-promise-basics/article.md
  1-js/11-async/07-microtask-queue/article.md
  1-js/12-generators-iterators/2-async-iterators-generators/article.md
  2-ui/1-document/10-size-and-scroll-window/article.md
  4-binary/03-blob/article.md
  5-network/11-websocket/article.md
  6-data-storage/03-indexeddb/article.md
  9-regular-expressions/05-regexp-multiline-mode/article.md
Labels: review needed

#290 Shadow DOM and events
  8-web-components/3-shadow-dom/article.md
Labels: needs +1

#287 JavaScript animations
  7-animation/3-js-animation/1-animate-ball/solution.md
  7-animation/3-js-animation/1-animate-ball/task.md
  7-animation/3-js-animation/2-animate-ball-hops/solution.md
  7-animation/3-js-animation/2-animate-ball-hops/task.md
  7-animation/3-js-animation/article.md
  7-animation/3-js-animation/move-raf.view/index.html
  7-animation/index.md
Labels: needs +1, review needed

#291 ArrayBuffer, binary arrays
  4-binary/01-arraybuffer-binary-arrays/01-concat/_js.view/solution.js
  4-binary/01-arraybuffer-binary-arrays/01-concat/_js.view/source.js
  4-binary/01-arraybuffer-binary-arrays/01-concat/task.md
  4-binary/01-arraybuffer-binary-arrays/article.md
Labels: needs +1

#292 TextDecoder and TextEncoder
  4-binary/02-text-decoder/article.md
Labels: needs +1

#293 Word boundary: \b
  9-regular-expressions/06-regexp-boundary/1-find-time-hh-mm/task.md
  9-regular-expressions/06-regexp-boundary/article.md
Labels: 2n review done

#297 Review Browser environment, specs
  2-ui/1-document/01-browser-environment/article.md
Labels: needs +1

#300 Review DOM tree
  2-ui/1-document/02-dom-nodes/article.md
Labels: needs +1

#301 Review Introduction to browser events
  2-ui/2-events/01-introduction-browser-events/01-hide-other/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.view/index.html
  2-ui/2-events/01-introduction-browser-events/06-hide-message/task.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/source.view/index.html
Labels: review needed

#302 Review Event delegation
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/source.view/index.html
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/solution.view/index.html
  2-ui/2-events/03-event-delegation/2-sliding-tree/task.md
  2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html
  2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html
  2-ui/2-events/03-event-delegation/3-sortable-table/task.md
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/solution.view/index.html
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/source.view/index.html
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
Labels: review needed

#303 Review Browser default actions
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/solution.view/index.html
  2-ui/2-events/04-default-browser-action/3-image-gallery/source.view/index.html
  2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
  2-ui/2-events/04-default-browser-action/article.md
  2-ui/2-events/04-default-browser-action/menu.view/menu.js
Labels: needs +1

#304 Review Mouse events
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/solution.view/index.html
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/source.view/index.html
  2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/task.md
Labels: needs +1

#305 Review Moving the mouse: mouseover/out, mouseenter/leave
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/solution.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/source.view/index.html
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
Labels: needs +1

#306 Review Drag'n'Drop with mouse events
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
Labels: needs +1

#308 Sets and ranges
  9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/solution.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/task.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/solution.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/task.md
  9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
Labels: 2nd review done, needs +1

#295 Blob
  4-binary/03-blob/article.md
Labels: needs +1

#296 File and FileReader
  4-binary/04-file/article.md
Labels: needs +1

#310 Review Events: change, input, cut, copy, paste
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/source.view/index.html
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/task.md
Labels: needs +1

#311 Review Forms: event and method submit
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.view/index.html
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
Labels: needs +1

#312 Review Page: DOMContentLoaded, load, beforeunload, unload
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
  2-ui/5-loading/01-onload-ondomcontentloaded/readystate.view/index.html
Labels: needs +1

#307 Template element
  8-web-components/4-template-element/article.md
Labels: 2nd review done, needs +1
