Repository javascript-tutorial/it.javascript.info, pull requests merged in 2021-05, with the labels that each got.

#313 Review Scripts: async, defer
  2-ui/5-loading/02-script-async-defer/article.md
  2-ui/5-loading/02-script-async-defer/long.js
  2-ui/5-loading/02-script-async-defer/small.js
Labels: review needed

#314 Review Resource loading: onload and onerror
  2-ui/5-loading/03-onload-onerror/1-load-img-callback/source.view/index.html
  2-ui/5-loading/03-onload-onerror/article.md
Labels: review needed

#315 Review Cookies, document.cookie
  6-data-storage/01-cookie/article.md
  6-data-storage/01-cookie/cookie.js
  6-data-storage/index.md
Labels: review needed

#316 Review LocalStorage, sessionStorage
  6-data-storage/02-localstorage/1-form-autosave/task.md
  6-data-storage/02-localstorage/article.md
Labels: review needed

#318 Greedy and lazy quantifiers
  9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/1-lazy-greedy/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/3-find-html-comments/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/3-find-html-comments/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/solution.md
  9-regular-expressions/10-regexp-greedy-and-lazy/4-find-html-tags-greedy-lazy/task.md
  9-regular-expressions/10-regexp-greedy-and-lazy/article.md
Labels: needs +1

#319 Review Patterns and flags
  9-regular-expressions/01-regexp-introduction/article.md
Labels: review needed

#320 Capturing groups
  9-regular-expressions/11-regexp-groups/01-test-mac/solution.md
  9-regular-expressions/11-regexp-groups/01-test-mac/task.md
  9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/solution.md
  9-regular-expressions/11-regexp-groups/02-find-webcolor-3-or-6/task.md
  9-regular-expressions/11-regexp-groups/03-find-decimal-numbers/solution.md
  9-regular-expressions/11-regexp-groups/03-find-decimal-numbers/task.md
  9-regular-expressions/11-regexp-groups/04-parse-expression/solution.md
  9-regular-expressions/11-regexp-groups/04-parse-expression/task.md
  9-regular-expressions/11-regexp-groups/article.md
Labels: needs +1

#321 Backreferences in pattern: \N and \k<name>
  9-regular-expressions/12-regexp-backreferences/article.md
Labels: 2nd review done, ready to merge
