Repository javascript-tutorial/it.javascript.info, pull requests merged in 2021-01, with the labels that each got.

#155 02-selection-range/article.md
  2-ui/99-ui-misc/02-selection-range/article.md
  5-network/12-server-sent-events/article.md
Labels: needs +1

#157 Hotfix conflicts
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/article.md
  1-js/04-object-basics/06-constructor-new/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
  1-js/05-data-types/08-weakmap-weakset/01-recipients-read/solution.md
  1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/task.md
  1-js/05-data-types/12-json/2-serialize-event-circular/task.md
  1-js/13-modules/01-modules-intro/article.md
  1-js/99-js-misc/04-reference-type/3-why-this/solution.md
  2-ui/5-loading/02-script-async-defer/article.md
  2-ui/5-loading/03-onload-onerror/article.md
  2-ui/99-ui-misc/01-mutation-observer/article.md
  2-ui/99-ui-misc/03-event-loop/article.md
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/01-fetch/01-fetch-users/task.md
  5-network/01-fetch/article.md
  5-network/02-formdata/article.md
  5-network/03-fetch-progress/article.md
  5-network/05-fetch-crossorigin/1-do-we-need-origin/task.md
  5-network/05-fetch-crossorigin/article.md
  6-data-storage/01-cookie/article.md
  6-data-storage/02-localstorage/article.md
  9-regular-expressions/01-regexp-introduction/article.md
  9-regular-expressions/04-regexp-anchors/1-start-end/solution.md
  9-regular-expressions/06-regexp-boundary/1-find-time-hh-mm/task.md
  9-regular-expressions/09-regexp-quantifiers/1-find-text-manydots/solution.md
  9-regular-expressions/09-regexp-quantifiers/1-find-text-manydots/task.md
  9-regular-expressions/09-regexp-quantifiers/2-find-html-colors-6hex/solution.md
  9-regular-expressions/09-regexp-quantifiers/2-find-html-colors-6hex/task.md
  9-regular-expressions/09-regexp-quantifiers/article.md
  9-regular-expressions/11-regexp-groups/01-test-mac/task.md
Labels: review needed

#151 Corretto ed aggiornato articolo ed esercizi 02/09-comparison
  1-js/02-first-steps/09-comparison/1-comparison-questions/solution.md
  1-js/02-first-steps/09-comparison/1-comparison-questions/task.md
  1-js/02-first-steps/09-comparison/article.md
Labels: needs +1, review needed

#145 Data types
  1-js/02-first-steps/05-types/1-string-quotes/solution.md
  1-js/02-first-steps/05-types/article.md
Labels: ready to merge

#162 Arrow functions, the basics
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/task.md
  1-js/02-first-steps/17-arrow-functions-basics/article.md
Labels: changes requested

#159 review 'Interaction: alert, prompt, confirm'
  1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
Labels: needs +1

#160 review 'Type Conversions'
  1-js/02-first-steps/07-type-conversions/article.md
Labels: needs +1

#161 review and update 'Debugging Chrome'
  1-js/03-code-quality/01-debugging-chrome/article.md
Labels: needs +1

#166 Selection and Range
  2-ui/99-ui-misc/02-selection-range/article.md
Labels: needs +1

#164 Improve contributing.md
  CONTRIBUTING.md
Labels: changes requested

#163 Custom errors, extending Error
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md
  1-js/10-error-handling/2-custom-errors/article.md
Labels: needs +1

#170 Comments
  1-js/03-code-quality/03-comments/article.md
Labels: needs +1

#169 Coding Style
  1-js/03-code-quality/02-coding-style/article.md
Labels: needs +1

#174 Revisione secondo articolo
  1-js/01-getting-started/2-manuals-specifications/article.md
Labels: needs +1

#168 Alcune piccole modifiche
  1-js/01-getting-started/1-intro/article.md
Labels: needs +1

#176 Revisione terzo articolo.
  1-js/01-getting-started/3-code-editors/article.md
Labels: needs +1

#177 Typo + inversione parole
  1-js/04-object-basics/01-object/article.md
Labels: needs +1

#173 Automated testing with Mocha
  1-js/03-code-quality/05-testing-mocha/article.md
Labels: needs +1

#171 Ninja code
  1-js/03-code-quality/04-ninja-code/article.md
Labels: needs +1

#172 Polyfills
  1-js/03-code-quality/06-polyfills/article.md
Labels: needs +1

#180 Server Sent Events
  5-network/12-server-sent-events/article.md
Labels: changes requested, needs +1

#181 Logical operators
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/solution.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
  1-js/02-first-steps/11-logical-operators/8-if-question/solution.md
  1-js/02-first-steps/11-logical-operators/8-if-question/task.md
  1-js/02-first-steps/11-logical-operators/9-check-login/task.md
  1-js/02-first-steps/11-logical-operators/article.md
Labels: needs +1

#182 Object references and copying
  1-js/04-object-basics/02-object-copy/article.md
Labels: needs +1, review needed

#183 Introduction to browser events
  2-ui/2-events/01-introduction-browser-events/article.md
Labels: needs +1

#186 updated CONTRIBUTING
  CONTRIBUTING.md
Labels: needs +1

#185 update README
  README.md
Labels: needs +1

#187 Optional chaining '?.'
  1-js/04-object-basics/07-optional-chaining/article.md
Labels: needs +1, review needed

#190 improve CONTRIBUTING.md
  CONTRIBUTING.md
Labels: needs +1

#188 Introduction to browser events
  2-ui/2-events/01-introduction-browser-events/01-hide-other/task.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
  2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
  2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
  2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/solution.md
  2-ui/2-events/01-introduction-browser-events/05-sliding-menu/task.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.md
  2-ui/2-events/01-introduction-browser-events/06-hide-message/task.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/solution.md
  2-ui/2-events/01-introduction-browser-events/07-carousel/task.md
Labels: needs +1

#191 13 while for
  1-js/02-first-steps/13-while-for/1-loop-last-value/solution.md
  1-js/02-first-steps/13-while-for/1-loop-last-value/task.md
  1-js/02-first-steps/13-while-for/2-which-value-while/solution.md
  1-js/02-first-steps/13-while-for/2-which-value-while/task.md
  1-js/02-first-steps/13-while-for/3-which-value-for/solution.md
  1-js/02-first-steps/13-while-for/3-which-value-for/task.md
  1-js/02-first-steps/13-while-for/4-for-even/solution.md
  1-js/02-first-steps/13-while-for/4-for-even/task.md
  1-js/02-first-steps/13-while-for/5-replace-for-while/task.md
  1-js/02-first-steps/13-while-for/6-repeat-until-correct/solution.md
  1-js/02-first-steps/13-while-for/6-repeat-until-correct/task.md
  1-js/02-first-steps/13-while-for/7-list-primes/solution.md
  1-js/02-first-steps/13-while-for/7-list-primes/task.md
  1-js/02-first-steps/13-while-for/article.md
Labels: needs +1

#193 if else
  1-js/02-first-steps/10-ifelse/1-if-zero-string/solution.md
  1-js/02-first-steps/10-ifelse/2-check-standard/task.md
  1-js/02-first-steps/10-ifelse/3-sign/task.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/task.md
  1-js/02-first-steps/10-ifelse/article.md
  1-js/02-first-steps/13-while-for/article.md
Labels: needs +1

#192 Long polling
  5-network/10-long-polling/article.md
Labels: needs +1

#195 Articolo/nullish operator
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
Labels: needs +1, review needed

#197 revisione articolo switch
  1-js/02-first-steps/14-switch/1-rewrite-switch-if-else/solution.md
  1-js/02-first-steps/14-switch/2-rewrite-if-switch/solution.md
  1-js/02-first-steps/14-switch/2-rewrite-if-switch/task.md
  1-js/02-first-steps/14-switch/article.md
Labels: needs +1

#194 The "new Function" syntax
  1-js/05-data-types/04-array/article.md
  1-js/06-advanced-functions/07-new-function/article.md
  1-js/09-classes/01-class/article.md
  1-js/09-classes/02-class-inheritance/article.md
Labels: changes requested, needs +1

#184 WeakMap and WeakSet
  1-js/05-data-types/07-map-set-weakmap-weakset/article.md
  1-js/05-data-types/08-weakmap-weakset/01-recipients-read/solution.md
  1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/solution.md
  1-js/05-data-types/08-weakmap-weakset/article.md
Labels: needs +1
