Repository javascript-tutorial/it.javascript.info, pull requests merged in 2021-03, with the labels that each got.

#236 Moving the mouse: mouseover/out, mouseenter/leave
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.view/hoverIntent.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/source.view/hoverIntent.js
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
  2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/mouseenter-mouseleave-delegation-2.view/script.js
Labels: review needed

#231 Static properties and methods
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/solution.md
  1-js/09-classes/03-static-properties-methods/3-class-extend-object/task.md
  1-js/09-classes/03-static-properties-methods/article.md
Labels: needs +1

#235 review iterables
  1-js/05-data-types/06-iterable/article.md
Labels: needs +1

#233 Arrow functions revisited
  1-js/06-advanced-functions/12-arrow-functions/article.md
Labels: needs +1

#239 Article/weakmap weakset
  1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set/03-iterable-keys/task.md
  1-js/05-data-types/07-map-set/article.md
  1-js/05-data-types/08-weakmap-weakset/01-recipients-read/solution.md
  1-js/05-data-types/08-weakmap-weakset/02-recipients-when-read/task.md
  1-js/05-data-types/08-weakmap-weakset/article.md
Labels: needs +1

#238 review map-set
  1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set/03-iterable-keys/task.md
  1-js/05-data-types/07-map-set/article.md
Labels: review needed

#247 Chapter titles translation
  1-js/05-data-types/index.md
  1-js/06-advanced-functions/index.md
  1-js/07-object-properties/index.md
  1-js/12-generators-iterators/index.md
Labels: needs +1

#237 Extending built-in classes
  1-js/09-classes/05-extend-natives/article.md
Labels: needs +1

#248 Object.keys, values, entries
  1-js/05-data-types/09-keys-values-entries/01-sum-salaries/solution.md
  1-js/05-data-types/09-keys-values-entries/02-count-properties/task.md
  1-js/05-data-types/09-keys-values-entries/article.md
Labels: needs +1

#240 Private and protected properties and method
  1-js/09-classes/04-private-protected-properties-methods/article.md
  1-js/09-classes/index.md
Labels: needs +1, ready to merge

#241 Class checking: "instanceof"
  1-js/09-classes/06-instanceof/1-strange-instanceof/solution.md
  1-js/09-classes/06-instanceof/1-strange-instanceof/task.md
  1-js/09-classes/06-instanceof/article.md
Labels: 2n review done

#242 Mixins
  1-js/09-classes/07-mixins/article.md
Labels: 2n review done

#243 Export and Import
  1-js/13-modules/02-import-export/article.md
Labels: 2n review done

#244 Dynamic imports
  1-js/13-modules/03-modules-dynamic-imports/article.md
  1-js/13-modules/03-modules-dynamic-imports/say.view/index.html
Labels: 2n review done

#246 Eval: run a code string
  1-js/99-js-misc/02-eval/1-eval-calculator/solution.md
  1-js/99-js-misc/02-eval/1-eval-calculator/task.md
  1-js/99-js-misc/02-eval/article.md
Labels: needs +1

#249 review Destructuring assignment
  1-js/05-data-types/10-destructuring-assignment/1-destruct-user/task.md
  1-js/05-data-types/10-destructuring-assignment/article.md
Labels: needs +1

#250 json review
  1-js/05-data-types/12-json/1-serialize-object/task.md
  1-js/05-data-types/12-json/2-serialize-event-circular/solution.md
  1-js/05-data-types/12-json/2-serialize-event-circular/task.md
  1-js/05-data-types/12-json/article.md
Labels: needs +1

#254 Searching: getElement*, querySelector*
  2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md
  2-ui/1-document/04-searching-elements-dom/1-find-elements/task.md
  2-ui/1-document/04-searching-elements-dom/article.md
Labels: 2n review done, ready to merge

#259 fix typo
  6-data-storage/01-cookie/article.md
Labels: needs +1

#253 Walking the DOM
  2-ui/1-document/03-dom-navigation/1-dom-children/solution.md
  2-ui/1-document/03-dom-navigation/1-dom-children/task.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/solution.md
  2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/task.md
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/solution.md
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/source.view/index.html
  2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/task.md
  2-ui/1-document/03-dom-navigation/article.md
Labels: 2n review done, needs +1, ready to merge

#252 Drag'n'Drop with mouse events
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/source.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.md
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.css
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/soccer.js
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/index.html
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/soccer.css
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/soccer.js
  2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
  2-ui/3-event-details/4-mouse-drag-and-drop/article.md
  2-ui/3-event-details/4-mouse-drag-and-drop/ball4.view/index.html
Labels: 2n review done, review needed

#257 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: needs +1, utilities

#255 Currying
  1-js/99-js-misc/03-currying-partials/article.md
Labels: needs +1

#256 Reference Type
  1-js/99-js-misc/04-reference-type/article.md
Labels: needs +1

#264 Sync
  1-js/02-first-steps/11-logical-operators/article.md
  1-js/02-first-steps/13-while-for/article.md
  1-js/04-object-basics/02-object-copy/article.md
  1-js/05-data-types/02-number/article.md
  1-js/05-data-types/03-string/article.md
  1-js/09-classes/03-static-properties-methods/article.md
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/solution.md
  1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md
  1-js/10-error-handling/1-try-catch/article.md
  1-js/11-async/05-promise-api/article.md
  1-js/13-modules/02-import-export/article.md
  2-ui/4-forms-controls/1-form-elements/article.md
  5-network/06-fetch-api/article.md
  6-data-storage/03-indexeddb/article.md
  9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
Labels: ready to merge

#262 Translate chapters' headers
  1-js/01-getting-started/index.md
  1-js/02-first-steps/index.md
  1-js/03-code-quality/index.md
  1-js/07-object-properties/index.md
  1-js/index.md
  2-ui/1-document/index.md
  2-ui/2-events/index.md
  2-ui/3-event-details/index.md
  2-ui/4-forms-controls/index.md
  2-ui/index.md
Labels: ready to merge, utilities

#260 Pointer events
  2-ui/3-event-details/6-pointer-events/article.md
  2-ui/3-event-details/6-pointer-events/slider.view/index.html
Labels: 2n review done, review needed

#258 BigInt
  1-js/99-js-misc/05-bigint/article.md
Labels: 2n review done

#261 Proxy and Reflect
  1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
  1-js/99-js-misc/01-proxy/02-array-negative/solution.md
  1-js/99-js-misc/01-proxy/02-array-negative/task.md
  1-js/99-js-misc/01-proxy/03-observable/solution.md
  1-js/99-js-misc/01-proxy/03-observable/task.md
  1-js/99-js-misc/01-proxy/article.md
Labels: 2n review done

#268 Node properties: type, tag and contents
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-lastchild-nodetype-inline/task.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.md
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/source.view/index.html
  2-ui/1-document/05-basic-dom-node-properties/2-tree-info/task.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/solution.md
  2-ui/1-document/05-basic-dom-node-properties/3-tag-in-comment/task.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/solution.md
  2-ui/1-document/05-basic-dom-node-properties/4-where-document-in-hierarchy/task.md
  2-ui/1-document/05-basic-dom-node-properties/article.md
Labels: 2n review done, needs +1

#267 Attributes and properties
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/task.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/task.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: ready to merge

#265 Keyboard: keydown and keyup
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.md
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.view/index.html
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/task.md
  2-ui/3-event-details/7-keyboard-events/article.md
Labels: ready to merge

#266 Scrolling
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.md
  2-ui/3-event-details/8-onscroll/1-endless-page/solution.view/index.html
  2-ui/3-event-details/8-onscroll/1-endless-page/source.view/index.html
  2-ui/3-event-details/8-onscroll/1-endless-page/task.md
  2-ui/3-event-details/8-onscroll/2-updown-button/solution.view/index.html
  2-ui/3-event-details/8-onscroll/2-updown-button/source.view/index.html
  2-ui/3-event-details/8-onscroll/2-updown-button/task.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/solution.md
  2-ui/3-event-details/8-onscroll/3-load-visible-img/solution.view/index.html
  2-ui/3-event-details/8-onscroll/3-load-visible-img/source.view/index.html
  2-ui/3-event-details/8-onscroll/3-load-visible-img/task.md
  2-ui/3-event-details/8-onscroll/article.md
Labels: needs +1

#271 URL objects
  5-network/07-url/article.md
Labels: needs +1, review needed

#272 Styles and classes
  2-ui/1-document/08-styles-and-classes/2-create-notification/solution.view/index.html
  2-ui/1-document/08-styles-and-classes/2-create-notification/source.view/index.html
  2-ui/1-document/08-styles-and-classes/2-create-notification/task.md
  2-ui/1-document/08-styles-and-classes/article.md
Labels: ready to merge

#269 Popups and window methods
  3-frames-and-windows/01-popup-windows/article.md
Labels: needs +1, review needed
