Repository javascript-tutorial/it.javascript.info, pull requests merged in 2021-06, with the labels that each got.

#322 Shadow DOM styling
  8-web-components/6-shadow-dom-style/article.md
Labels: needs +1, review needed

#326 Sincronizzazione con versione inglese
  1-js/01-getting-started/1-intro/article.md
  1-js/02-first-steps/02-structure/article.md
  1-js/02-first-steps/05-types/article.md
  1-js/02-first-steps/08-operators/article.md
  1-js/02-first-steps/15-function-basics/article.md
  1-js/03-code-quality/01-debugging-chrome/article.md
  1-js/04-object-basics/06-constructor-new/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
  1-js/05-data-types/01-primitives-methods/article.md
  1-js/05-data-types/03-string/article.md
  1-js/05-data-types/04-array/article.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
  1-js/09-classes/01-class/article.md
  1-js/09-classes/04-private-protected-properties-methods/article.md
  1-js/13-modules/01-modules-intro/article.md
  1-js/99-js-misc/04-reference-type/article.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/task.md
  2-ui/4-forms-controls/2-focus-blur/article.md
  2-ui/5-loading/01-onload-ondomcontentloaded/article.md
  6-data-storage/01-cookie/article.md
  6-data-storage/02-localstorage/article.md
  6-data-storage/03-indexeddb/article.md
  8-web-components/6-shadow-dom-style/article.md
  9-regular-expressions/07-regexp-escaping/article.md
  9-regular-expressions/15-regexp-catastrophic-backtracking/article.md
  9-regular-expressions/17-regexp-methods/article.md
Labels: review needed

#323 Alternation (OR) |
  9-regular-expressions/13-regexp-alternation/01-find-programming-language/solution.md
  9-regular-expressions/13-regexp-alternation/01-find-programming-language/task.md
  9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/solution.md
  9-regular-expressions/13-regexp-alternation/02-find-matching-bbtags/task.md
  9-regular-expressions/13-regexp-alternation/03-match-quoted-string/solution.md
  9-regular-expressions/13-regexp-alternation/03-match-quoted-string/task.md
  9-regular-expressions/13-regexp-alternation/04-match-exact-tag/solution.md
  9-regular-expressions/13-regexp-alternation/04-match-exact-tag/task.md
  9-regular-expressions/13-regexp-alternation/article.md
Labels: needs +1

#324 Lookahead and lookbehind
  9-regular-expressions/14-regexp-lookahead-lookbehind/1-find-non-negative-integers/solution.md
  9-regular-expressions/14-regexp-lookahead-lookbehind/1-find-non-negative-integers/task.md
  9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/solution.md
  9-regular-expressions/14-regexp-lookahead-lookbehind/2-insert-after-head/task.md
  9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
Labels: needs +1

#328 Sync
  1-js/03-code-quality/06-polyfills/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
  1-js/05-data-types/02-number/article.md
  1-js/09-classes/04-private-protected-properties-methods/article.md
  1-js/11-async/01-callbacks/article.md
  1-js/11-async/05-promise-api/article.md
  2-ui/3-event-details/7-keyboard-events/article.md
  6-data-storage/01-cookie/article.md
  6-data-storage/01-cookie/cookie.js
Labels: review needed
