Repository javascript-tutorial/it.javascript.info, pull requests merged in 2021-02, with the labels that each got.

#196 Property flags and descriptors
  1-js/07-object-properties/01-property-descriptors/article.md
Labels: needs +1

#198 Bubbling and capturing
  2-ui/2-events/02-bubbling-and-capturing/article.md
Labels: needs +1

#200 Articolo/14 functions
  1-js/02-first-steps/15-function-basics/1-if-else-required/task.md
  1-js/02-first-steps/15-function-basics/2-rewrite-function-question-or/task.md
  1-js/02-first-steps/15-function-basics/3-min/solution.md
  1-js/02-first-steps/15-function-basics/4-pow/task.md
  1-js/02-first-steps/15-function-basics/article.md
Labels: needs +1

#199 Property getters and setters
  1-js/07-object-properties/02-property-accessors/article.md
Labels: needs +1

#202 articolo function expressions
  1-js/02-first-steps/16-function-expressions/article.md
Labels: ready to merge

#206 revisione - Symbol type
  1-js/04-object-basics/08-symbol/article.md
Labels: needs +1

#203 Event delegation
  2-ui/2-events/03-event-delegation/article.md
Labels: needs +1

#201 Dispatching custom events
  2-ui/2-events/05-dispatch-events/article.md
Labels: needs +1

#205 Event delegation - task and solutions
  2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/solution.md
  2-ui/2-events/03-event-delegation/2-sliding-tree/task.md
  2-ui/2-events/03-event-delegation/3-sortable-table/task.md
  2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md
Labels: needs +1

#209 revisione articolo oggetti
  1-js/04-object-basics/01-object/2-hello-object/task.md
  1-js/04-object-basics/01-object/3-is-empty/solution.md
  1-js/04-object-basics/01-object/4-const-object/solution.md
  1-js/04-object-basics/01-object/4-const-object/task.md
  1-js/04-object-basics/01-object/5-sum-object/task.md
  1-js/04-object-basics/01-object/8-multiply-numeric/solution.md
  1-js/04-object-basics/01-object/article.md
Labels: needs +1

#211 revisione articolo su this
  1-js/04-object-basics/04-object-methods/4-object-property-this/solution.md
  1-js/04-object-basics/04-object-methods/4-object-property-this/task.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/task.md
  1-js/04-object-basics/04-object-methods/article.md
Labels: needs +1

#207 Prototypal inheritance
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/solution.md
  1-js/08-prototypes/01-prototype-inheritance/1-property-after-delete/task.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/solution.md
  1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/task.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/solution.md
  1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/task.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
  1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md
  1-js/08-prototypes/01-prototype-inheritance/article.md
Labels: needs +1

#215 revisione articolo optional chaining
  1-js/04-object-basics/07-optional-chaining/article.md
Labels: needs +1

#204 Decorators and forwarding, call/apply
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/_js.view/solution.js
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/_js.view/source.js
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/01-spy-decorator/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/02-delay/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/debounce.view/index.html
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/_js.view/solution.js
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/_js.view/test.js
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/solution.md
  1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
  1-js/06-advanced-functions/09-call-apply-decorators/article.md
Labels: needs +1

#218 Sync
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/solution.md
  1-js/02-first-steps/08-operators/3-primitive-conversions-questions/task.md
  1-js/02-first-steps/11-logical-operators/article.md
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
  1-js/02-first-steps/17-arrow-functions-basics/article.md
  1-js/04-object-basics/02-object-copy/article.md
  1-js/04-object-basics/04-object-methods/8-chain-calls/solution.md
  1-js/04-object-basics/07-optional-chaining/article.md
  1-js/05-data-types/10-destructuring-assignment/6-max-salary/_js.view/solution.js
  1-js/05-data-types/10-destructuring-assignment/article.md
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
  1-js/06-advanced-functions/05-global-object/article.md
  1-js/06-advanced-functions/12-arrow-functions/article.md
  1-js/11-async/02-promise-basics/article.md
  1-js/13-modules/02-import-export/article.md
  2-ui/1-document/07-modifying-document/1-createtextnode-vs-innerhtml/task.md
Labels: review needed

#216 revisione articolo objects to primitive conversion
  1-js/04-object-basics/09-object-toprimitive/article.md
Labels: review needed

#214 new operator article
  1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/solution.md
  1-js/04-object-basics/06-constructor-new/article.md
Labels: review needed

#208 F.prototype
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/solution.md
  1-js/08-prototypes/02-function-prototype/1-changing-prototype/task.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/solution.md
  1-js/08-prototypes/02-function-prototype/4-new-object-same-constructor/task.md
  1-js/08-prototypes/02-function-prototype/article.md
Labels: needs +1

#212 Browser default actions
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
  2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
  2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
  2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
  2-ui/2-events/04-default-browser-action/article.md
Labels: needs +1

#219 reviewed article and exercises
  1-js/04-object-basics/07-optional-chaining/article.md
  1-js/05-data-types/01-primitives-methods/1-string-new-property/solution.md
  1-js/05-data-types/01-primitives-methods/article.md
Labels: needs +1

#220 reviewed article and exercises
  1-js/05-data-types/02-number/1-sum-interface/task.md
  1-js/05-data-types/02-number/3-repeat-until-number/solution.md
  1-js/05-data-types/02-number/4-endless-loop-error/solution.md
  1-js/05-data-types/02-number/8-random-min-max/solution.md
  1-js/05-data-types/02-number/8-random-min-max/task.md
  1-js/05-data-types/02-number/article.md
Labels: needs +1

#222 Fetch api
  5-network/06-fetch-api/article.md
Labels: needs +1

#221 Arrays
  1-js/05-data-types/04-array/1-item-value/task.md
  1-js/05-data-types/04-array/10-maximal-subarray/task.md
  1-js/05-data-types/04-array/2-create-array/task.md
  1-js/05-data-types/04-array/3-call-array-this/solution.md
  1-js/05-data-types/04-array/3-call-array-this/task.md
  1-js/05-data-types/04-array/5-array-input-sum/solution.md
  1-js/05-data-types/04-array/5-array-input-sum/task.md
  1-js/05-data-types/04-array/article.md
Labels: needs +1, review needed

#210 Native prototypes
  1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/solution.md
  1-js/08-prototypes/03-native-prototypes/1-defer-to-prototype/task.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/solution.md
  1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/task.md
  1-js/08-prototypes/03-native-prototypes/article.md
Labels: needs +1

#213 Prototype methods, objects without __proto__
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/solution.md
  1-js/08-prototypes/04-prototype-methods/2-dictionary-tostring/task.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/solution.md
  1-js/08-prototypes/04-prototype-methods/3-compare-calls/task.md
  1-js/08-prototypes/04-prototype-methods/article.md
Labels: needs +1

#224 Review Strings
  1-js/05-data-types/03-string/3-truncate/task.md
  1-js/05-data-types/03-string/4-extract-currency/task.md
  1-js/05-data-types/03-string/article.md
Labels: needs +1

#229 Function binding
  1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/solution.md
  1-js/06-advanced-functions/10-bind/2-write-to-object-after-bind/task.md
  1-js/06-advanced-functions/10-bind/3-second-bind/solution.md
  1-js/06-advanced-functions/10-bind/3-second-bind/task.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/solution.md
  1-js/06-advanced-functions/10-bind/4-function-property-after-bind/task.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
  1-js/06-advanced-functions/10-bind/5-question-use-bind/task.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/solution.md
  1-js/06-advanced-functions/10-bind/6-ask-partial/task.md
  1-js/06-advanced-functions/10-bind/article.md
Labels: needs +1, review needed

#223 Events: change, input, cut, copy, paste
  2-ui/4-forms-controls/3-events-change-input/1-deposit-calculator/task.md
  2-ui/4-forms-controls/3-events-change-input/article.md
Labels: needs +1

#226 Form properties and methods
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
Labels: needs +1

#227 Focusing: focus/blur
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/1-form-elements/article.md
  2-ui/4-forms-controls/2-focus-blur/3-editable-div/task.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/solution.md
  2-ui/4-forms-controls/2-focus-blur/4-edit-td-click/task.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/solution.md
  2-ui/4-forms-controls/2-focus-blur/5-keyboard-mouse/task.md
  2-ui/4-forms-controls/2-focus-blur/article.md
Labels: needs +1

#234 Forms: event and method submit
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
  2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.md
  2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
  2-ui/4-forms-controls/4-forms-submit/article.md
Labels: review needed

#230 array methods review
  1-js/05-data-types/05-array-methods/1-camelcase/_js.view/solution.js
  1-js/05-data-types/05-array-methods/1-camelcase/task.md
  1-js/05-data-types/05-array-methods/10-average-age/task.md
  1-js/05-data-types/05-array-methods/11-array-unique/solution.md
  1-js/05-data-types/05-array-methods/11-array-unique/task.md
  1-js/05-data-types/05-array-methods/12-reduce-object/task.md
  1-js/05-data-types/05-array-methods/2-filter-range/_js.view/solution.js
  1-js/05-data-types/05-array-methods/2-filter-range/solution.md
  1-js/05-data-types/05-array-methods/2-filter-range/task.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/_js.view/solution.js
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/solution.md
  1-js/05-data-types/05-array-methods/3-filter-range-in-place/task.md
  1-js/05-data-types/05-array-methods/4-sort-back/task.md
  1-js/05-data-types/05-array-methods/5-copy-sort-array/task.md
  1-js/05-data-types/05-array-methods/6-array-get-names/task.md
  1-js/05-data-types/05-array-methods/6-calculator-extendable/task.md
  1-js/05-data-types/05-array-methods/7-map-objects/solution.md
  1-js/05-data-types/05-array-methods/7-map-objects/task.md
  1-js/05-data-types/05-array-methods/8-sort-objects/solution.md
  1-js/05-data-types/05-array-methods/8-sort-objects/task.md
  1-js/05-data-types/05-array-methods/9-shuffle/solution.md
  1-js/05-data-types/05-array-methods/9-shuffle/task.md
  1-js/05-data-types/05-array-methods/article.md
Labels: needs +1
